matlab.command=D:\\develop\\MatlabR2020a\\bin\\matlab.exe
matlab.timeout=300
matlab.batch-mode=-batch

matlab.single-instance=true

matlab.mode=auto

matlab.prewarm=true

python.command=/usr/local/python313/bin/python3.13
python.timeout=10
