spring.application.name=DateCreateJava
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

simulation.python.api-base-url=http://127.0.0.1:5000
simulation.python.api-connect-timeout-seconds=10
simulation.python.api-read-timeout-seconds=600
